### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by mctwynne** [jhlgns/naysayer88.vim#1]
Hello. Would you mind adding a license to this project so the community could fork and make changes if you wish to support that?

Thank you!

**Comment by jhlgns** [comment]
Thanks for your interest!
Done as of a6b07d8c310ce72d4e98eefde35f08adf4a61e0d.
It's now licensed under the MIT license. Have fun!

**Comment by mctwynne** [comment]
@jhlgns Awesome! Thanks a lot!
